"""empty message

Revision ID: 32d3c85305f0
Revises: 5d78b66df7b3
Create Date: 2023-11-07 14:01:59.496427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32d3c85305f0'
down_revision = '5d78b66df7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index('ix_doctors_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=55), nullable=True))
        batch_op.create_index('ix_doctors_username', ['username'], unique=False)

    # ### end Alembic commands ###
