"""empty message

Revision ID: 5d78b66df7b3
Revises: 
Create Date: 2023-11-07 13:28:53.967008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d78b66df7b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=55), nullable=True),
    sa.Column('first_name', sa.String(length=55), nullable=True),
    sa.Column('last_name', sa.String(length=55), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('kmpdc_license_num', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_kmpdc_license_num'), ['kmpdc_license_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialization'), ['specialization'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_username'), ['username'], unique=True)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('second_name', sa.String(length=60), nullable=True),
    sa.Column('surname', sa.String(length=60), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_second_name'), ['second_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_surname'), ['surname'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('second_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_second_name'), ['second_name'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=60), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_second_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_surname'))
        batch_op.drop_index(batch_op.f('ix_patients_second_name'))
        batch_op.drop_index(batch_op.f('ix_patients_gender'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))

    op.drop_table('patients')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_username'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialization'))
        batch_op.drop_index(batch_op.f('ix_doctors_phone_number'))
        batch_op.drop_index(batch_op.f('ix_doctors_last_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_kmpdc_license_num'))
        batch_op.drop_index(batch_op.f('ix_doctors_gender'))
        batch_op.drop_index(batch_op.f('ix_doctors_first_name'))
        batch_op.drop_index(batch_op.f('ix_doctors_email'))

    op.drop_table('doctors')
    # ### end Alembic commands ###
